# Generated by Django 4.2 on 2025-03-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_delivery_cart_location_cart_payments_cart_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery',
            field=models.CharField(blank=True, default='Processing', max_length=100, null=True),
        ),
    ]
