# Generated by Django 4.2 on 2025-03-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cart_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderid',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
