# Generated by Django 4.2 on 2025-03-14 08:41

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cart_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderid',
            field=models.CharField(default=apps.shop.models.generateOrderId, max_length=15, unique=True),
        ),
    ]
