# Generated by Django 4.2 on 2025-03-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_purchase',
            field=models.IntegerField(default=1),
        ),
    ]
