# Generated by Django 4.2 on 2025-03-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cartitem_price_at_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payments',
            field=models.CharField(blank=True, default='PENDING', max_length=100, null=True),
        ),
    ]
