# Generated by Django 4.2 on 2025-03-15 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_cart_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_id', models.CharField(max_length=100, null=True, unique=True)),
                ('amount', models.IntegerField(default=1)),
                ('payment_type', models.CharField(default='MPESA', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
